version: "3.8"

services:
  plausible_events_db:
    image: clickhouse/clickhouse-server:24.12-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - event-logs:/var/log/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_DB=plausible_events_db
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 -O - http://127.0.0.1:8123/ping || exit 1"]
      start_period: 1m

  plausible:
    image: us-central1-docker.pkg.dev/propellernet-analytics/plausible-repo/plausible:fix-duplicates
    restart: always
    command: sh -c "sleep 10 && (/app/bin/plausible eval 'Plausible.Release.interweave_migrate()' || true) && /app/bin/plausible start"
    depends_on:
      plausible_events_db:
        condition: service_healthy
    volumes:
      - plausible-data:/var/lib/plausible
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    environment:
      - DATABASE_URL=postgresql://postgres:SecurePlausiblePassword2025!@34.142.91.101/plausible
      - SECRET_KEY_BASE=SuperSecretKeyBaseForPlausibleThatIsVeryLongAndSecure2025Analytics
      - BASE_URL=https://analytics.propellernet.co.uk
      - TOTP_VAULT_KEY=DSHGn/hOD0VSg0CMvzZaFAUEnFBl1UiJAXcI7XikRtg=
      - BYPASS_AUTH=true
      - CLICKHOUSE_DATABASE_URL=http://plausible_events_db:8123/plausible_events_db
    ports:
      - "8000:8000"

volumes:
  event-data:
  event-logs:
  plausible-data:
