CREATE DATABASE IF NOT EXISTS plausible_events_db;

CREATE TABLE IF NOT EXISTS plausible_events_db.events_v2 (
    timestamp DateTime64(3) CODEC(DoubleDelta, LZ4),
    name LowCardinality(String),
    domain String,
    user_id UInt64,
    session_id UInt64,
    hostname LowCardinality(String),
    pathname String,
    referrer String,
    referrer_source String,
    utm_medium LowCardinality(String),
    utm_source LowCardinality(String),
    utm_campaign LowCardinality(String),
    utm_content String,
    utm_term String,
    country_code FixedString(2),
    subdivision1_code LowCardinality(String),
    subdivision2_code LowCardinality(String),
    city_geoname_id UInt32,
    screen_size LowCardinality(String),
    operating_system LowCardinality(String),
    operating_system_version LowCardinality(String),
    browser LowCardinality(String),
    browser_version LowCardinality(String),
    `meta.key` Array(String),
    `meta.value` Array(String),
    revenue_source_amount Nullable(Decimal64(3)),
    revenue_source_currency FixedString(3),
    revenue_reporting_amount Nullable(Decimal64(3)),
    revenue_reporting_currency FixedString(3),
    site_id UInt64 CODEC(DoubleDelta, ZSTD(1)),
    _sample_factor UInt8 DEFAULT 1 CODEC(ZSTD(1))
) ENGINE = MergeTree
PARTITION BY toYYYYMM(timestamp)
ORDER BY (site_id, toDate(timestamp), user_id, session_id, timestamp);

CREATE TABLE IF NOT EXISTS plausible_events_db.sessions_v2 (
    sign Int8 CODEC(ZSTD(1)),
    session_id UInt64,
    site_id UInt64 CODEC(DoubleDelta, ZSTD(1)),
    user_id UInt64,
    hostname LowCardinality(String),
    entry_page String,
    exit_page String,
    is_bounce UInt8,
    duration UInt32,
    pageviews Int32,
    events Int32,
    referrer String,
    referrer_source String,
    utm_medium LowCardinality(String),
    utm_source LowCardinality(String),
    utm_campaign LowCardinality(String),
    utm_content String,
    utm_term String,
    country_code FixedString(2),
    subdivision1_code LowCardinality(String),
    subdivision2_code LowCardinality(String),
    city_geoname_id UInt32,
    screen_size LowCardinality(String),
    operating_system LowCardinality(String),
    operating_system_version LowCardinality(String),
    browser LowCardinality(String),
    browser_version LowCardinality(String),
    timestamp DateTime,
    start DateTime CODEC(DoubleDelta, ZSTD(1)),
    revenue_source_amount Nullable(Decimal64(3)),
    revenue_source_currency FixedString(3),
    revenue_reporting_amount Nullable(Decimal64(3)),
    revenue_reporting_currency FixedString(3),
    _sample_factor UInt8 DEFAULT 1 CODEC(ZSTD(1))
) ENGINE = CollapsingMergeTree(sign)
PARTITION BY toYYYYMM(start)
ORDER BY (site_id, toDate(start), user_id, session_id, start);
